# Generated by Django 5.2.16 on 2026-07-19 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversionfunnel',
            index=models.Index(fields=['stage', 'reached_at'], name='analytics_c_stage_bf58e4_idx'),
        ),
    ]
