# Generated by Django 5.2.15 on 2026-06-25 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento vs. precio mensual equivalente (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('courses_limit', models.PositiveIntegerField(default=0, help_text='0 = acceso ilimitado')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('PENDING', 'Pendiente de Pago')], default='PENDING', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_last4', models.CharField(max_length=4)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=200)),
                ('is_successful', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='memberships.usermembership')),
            ],
        ),
    ]
