# Generated by Django 5.2.16 on 2026-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ciclo de facturación',
                'verbose_name_plural': 'Ciclos de facturación',
            },
        ),
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de membresía',
                'verbose_name_plural': 'Estados de membresía',
            },
        ),
    ]
