# Generated by Django 5.2.16 on 2026-07-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_seed_billing_cycles_and_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='billing_cycle',
            field=models.ForeignKey(db_column='billing_cycle', default='MONTHLY', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.billingcycle'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='status',
            field=models.ForeignKey(db_column='status', default='PENDING', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.membershipstatus'),
        ),
    ]
