# Generated by Django 5.2.16 on 2026-07-11 23:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Saldo simulado disponible para compras (demo, no es dinero real).', max_digits=10),
        ),
    ]
