# Generated by hand (equivalent to `makemigrations`) — the interactive
# "unique callable default" prompt from makemigrations can't be answered
# non-interactively through docker compose run on this environment.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=apps.users.models.generate_referral_code, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
