# Generated by Django 5.2.16 on 2026-07-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_roles_wallet_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(db_column='role', default='ALUMNO', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role'),
        ),
    ]
