# Generated by Django 5.2.16 on 2026-08-02 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teacherapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeStatus',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de recarga',
                'verbose_name_plural': 'Estados de recarga',
            },
        ),
        migrations.CreateModel(
            name='WalletRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('decline_reason', models.CharField(blank=True, default='', max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.rechargestatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recarga de saldo',
                'verbose_name_plural': 'Recargas de saldo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_walle_user_id_7cea1e_idx')],
            },
        ),
    ]
