# Generated by Django 5.2.16 on 2026-08-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seed_recharge_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_autocomplete_demo',
            field=models.BooleanField(default=False, help_text='Solo para la cuenta de revisión. Salta las actividades del curso.', verbose_name='Puede completar cursos de un clic (demo)'),
        ),
    ]
