# Generated by Django 5.2.16 on 2026-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_can_autocomplete_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_email',
            field=models.EmailField(blank=True, default='', help_text='Vacío = los correos van al email de la cuenta.', max_length=254, verbose_name='Correo para avisos'),
        ),
    ]
