# Generated by Django 5.2.16 on 2026-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField(default=0.5)),
            ],
            options={
                'verbose_name': 'Tipo de interacción',
                'verbose_name_plural': 'Tipos de interacción',
            },
        ),
    ]
