# Generated by Django 5.2.16 on 2026-07-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_seed_interaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseinteraction',
            name='interaction_type',
            field=models.ForeignKey(db_column='interaction_type', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recommendations.interactiontype'),
        ),
    ]
