# Generated by hand (equivalent to `makemigrations`) — see 0003 in apps/users
# for why: the interactive prompt for the users-app referral_code field blocks
# `makemigrations` even when scoped to a single app, since the autodetector
# scans all apps before filtering output.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento sobre el total (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Vacío = sin fecha de expiración', null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = usos ilimitados')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
