# Generated by Django 5.2.16 on 2026-07-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_seed_order_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(db_column='status', default='PENDING', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderstatus'),
        ),
    ]
