# Generated by Django 5.2.16 on 2026-07-14 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nivel de curso',
                'verbose_name_plural': 'Niveles de curso',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='Español', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='ck_review_rating_1_5'),
        ),
    ]
