# Generated by Django 5.2.16 on 2026-07-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_course_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(db_column='level', default='BASICO', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.courselevel'),
        ),
    ]
