# Generated by Django 5.2.16 on 2026-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio rebajado. Déjalo vacío si el curso no está en oferta.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='promo_until',
            field=models.DateTimeField(blank=True, help_text='Fin de la oferta. Vacío = sin fecha de término.', null=True),
        ),
    ]
