# Generated by Django 5.2.16 on 2026-08-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_course_promo_price_course_promo_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(help_text='Consigna: qué debe hacer y entregar el alumno')),
                ('resource_label', models.CharField(blank=True, default='', max_length=200)),
                ('resource_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='catalog.course')),
            ],
            options={
                'verbose_name': 'Trabajo práctico',
                'verbose_name_plural': 'Trabajos prácticos',
            },
        ),
    ]
