-- ============================================================
-- 01_usuarios.sql — Usuarios, saldo, recargas y postulación a docente
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 10
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: roles (catálogo)
-- Alumno, docente y administrador. Tabla de catálogo con clave
-- primaria natural: el código se usa tal cual en las FK, así el
-- valor es legible al consultar la base sin hacer JOIN.
-- ------------------------------------------------------------

CREATE TABLE public.roles (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: usuarios
-- Alumnos, docentes y administradores de la plataforma.
-- Incluye el saldo simulado (wallet) y el código de referidos.
-- ------------------------------------------------------------

CREATE TABLE public.usuarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrasena character varying(128) NOT NULL,
    ultimo_acceso timestamp with time zone,
    es_superusuario boolean NOT NULL,
    nombres character varying(150) NOT NULL,
    apellidos character varying(150) NOT NULL,
    es_staff boolean NOT NULL,
    esta_activo boolean NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    rol character varying(20) NOT NULL,
    ip_ultimo_acceso inet,
    email_verificado boolean NOT NULL,
    avatar character varying(100),
    biografia text,
    telefono character varying(20),
    saldo numeric(10,2) NOT NULL,
    codigo_referido character varying(12) NOT NULL,
    referido_por_id bigint,
    -- Atajo de demostración: permite dar por cumplido un curso entero de un
    -- clic para poder mostrar el certificado sin recorrer las lecciones una
    -- por una. Está apagado por defecto y solo se activa en la cuenta de
    -- revisión; en una plataforma real esta columna no existiría.
    puede_completar_demo boolean NOT NULL,
    -- A dónde mandar los avisos (factura, certificado, comprobante) cuando no
    -- deben ir al correo del login. Existe porque `email` es el usuario con el
    -- que se inicia sesión y además es único: sin esta columna, apuntar dos
    -- cuentas de demostración al mismo buzón real obligaría a romper sus
    -- credenciales. Vacío = se usa `email`.
    correo_avisos character varying(254) NOT NULL,

    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT uq_usuarios_codigo_referido UNIQUE (codigo_referido)
);

ALTER TABLE public.usuarios
    ADD CONSTRAINT fk_usuarios_rol
    FOREIGN KEY (rol) REFERENCES public.roles(codigo)
    DEFERRABLE INITIALLY DEFERRED;

-- Auto-relación: qué usuario refirió a este usuario (programa de referidos)
ALTER TABLE public.usuarios
    ADD CONSTRAINT fk_usuarios_referido_por
    FOREIGN KEY (referido_por_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_usuarios_rol ON public.usuarios (rol);
CREATE INDEX idx_usuarios_referido_por ON public.usuarios (referido_por_id);


-- ------------------------------------------------------------
-- Tabla: usuarios_grupos
-- Relación N:M entre usuarios y grupos de permisos.
-- (En la base real, grupo_id referencia a la tabla interna
--  de Django auth_group.)
-- ------------------------------------------------------------

CREATE TABLE public.usuarios_grupos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL,
    grupo_id integer NOT NULL,

    CONSTRAINT uq_usuarios_grupos UNIQUE (usuario_id, grupo_id)
);

ALTER TABLE public.usuarios_grupos
    ADD CONSTRAINT fk_usuarios_grupos_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_usuarios_grupos_usuario ON public.usuarios_grupos (usuario_id);
CREATE INDEX idx_usuarios_grupos_grupo ON public.usuarios_grupos (grupo_id);


-- ------------------------------------------------------------
-- Tabla: usuarios_permisos
-- Relación N:M entre usuarios y permisos individuales.
-- (En la base real, permiso_id referencia a la tabla interna
--  de Django auth_permission.)
-- ------------------------------------------------------------

CREATE TABLE public.usuarios_permisos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL,
    permiso_id integer NOT NULL,

    CONSTRAINT uq_usuarios_permisos UNIQUE (usuario_id, permiso_id)
);

ALTER TABLE public.usuarios_permisos
    ADD CONSTRAINT fk_usuarios_permisos_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_usuarios_permisos_usuario ON public.usuarios_permisos (usuario_id);
CREATE INDEX idx_usuarios_permisos_permiso ON public.usuarios_permisos (permiso_id);


-- ------------------------------------------------------------
-- Tabla: tipos_transaccion_saldo (catálogo)
-- Qué originó un movimiento del saldo: bono de bienvenida,
-- compra de cursos, pago de membresía, bono por referido.
-- ------------------------------------------------------------

CREATE TABLE public.tipos_transaccion_saldo (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: transacciones_saldo
-- Libro mayor de la billetera simulada. Cada fila registra el
-- monto del movimiento Y el saldo que quedó después, para poder
-- auditar el historial sin tener que recalcularlo.
-- ------------------------------------------------------------

CREATE TABLE public.transacciones_saldo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto numeric(10,2) NOT NULL,
    saldo_posterior numeric(10,2) NOT NULL,
    descripcion character varying(255) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL,
    tipo_transaccion character varying(20) NOT NULL
);

ALTER TABLE public.transacciones_saldo
    ADD CONSTRAINT fk_transacciones_saldo_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.transacciones_saldo
    ADD CONSTRAINT fk_transacciones_saldo_tipo
    FOREIGN KEY (tipo_transaccion) REFERENCES public.tipos_transaccion_saldo(codigo)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_transacciones_saldo_usuario ON public.transacciones_saldo (usuario_id);
CREATE INDEX idx_transacciones_saldo_tipo ON public.transacciones_saldo (tipo_transaccion);


-- ------------------------------------------------------------
-- Tabla: estados_recarga (catálogo)
-- Ciclo de vida de una recarga: PENDIENTE (creada, esperando que el
-- usuario autorice en la pasarela), APROBADA, RECHAZADA (la pasarela
-- negó la tarjeta), CANCELADA (el usuario abandonó) y EXPIRADA
-- (pasaron más de 15 minutos sin autorizar).
-- ------------------------------------------------------------

CREATE TABLE public.estados_recarga (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: recargas_saldo
-- Intento de recarga del saldo a través de la pasarela de pago
-- simulada.
--
-- Existe como registro propio, en vez de acreditar el saldo de una
-- sola vez, porque el flujo tiene DOS pasos separados en el tiempo:
-- primero se crea la intención con el monto, y después el usuario
-- autoriza en la pantalla de la pasarela. Guardar el estado permite:
--
--   1) que el monto NO viaje desde el navegador al autorizar (se lee
--      de aquí), así nadie puede pedir $5 y acreditarse $5000;
--   2) que una autorización reenviada no acredite dos veces: la fila
--      se bloquea y se verifica que siga PENDIENTE;
--   3) dejar historial de los intentos fallidos, no solo de los
--      exitosos.
--
-- El "token" es un UUID público que viaja en la URL de la pasarela:
-- al no ser secuencial, nadie puede adivinar el de otro usuario.
-- Del mismo modo que en las órdenes, el número de tarjeta nunca se
-- almacena: solo los 4 últimos dígitos.
-- ------------------------------------------------------------

CREATE TABLE public.recargas_saldo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token uuid NOT NULL,
    monto numeric(10,2) NOT NULL,
    ultimos4_tarjeta character varying(4) NOT NULL,
    motivo_rechazo character varying(120) NOT NULL,
    referencia character varying(40) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_completado timestamp with time zone,
    estado character varying(20) NOT NULL,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_recargas_saldo_token UNIQUE (token)
);

ALTER TABLE public.recargas_saldo
    ADD CONSTRAINT fk_recargas_saldo_estado
    FOREIGN KEY (estado) REFERENCES public.estados_recarga(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.recargas_saldo
    ADD CONSTRAINT fk_recargas_saldo_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_recargas_saldo_estado ON public.recargas_saldo (estado);
CREATE INDEX idx_recargas_saldo_usuario ON public.recargas_saldo (usuario_id);
-- Índice del historial: el listado siempre pide las recargas de un
-- usuario de la más reciente a la más antigua.
CREATE INDEX idx_recargas_saldo_usuario_fecha
    ON public.recargas_saldo (usuario_id, fecha_creacion DESC);


-- ------------------------------------------------------------
-- Tabla: estados_solicitud_docente (catálogo)
-- Pendiente, aprobada o rechazada.
-- ------------------------------------------------------------

CREATE TABLE public.estados_solicitud_docente (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: solicitudes_docente
-- Postulación de un alumno para convertirse en docente. Guarda
-- la cédula (obligatoria) y, opcionalmente, un documento de
-- credenciales. Al aprobarla, el rol del usuario cambia a DOCENTE.
-- ------------------------------------------------------------

CREATE TABLE public.solicitudes_docente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titular character varying(150) NOT NULL,
    biografia text NOT NULL,
    documento_identidad character varying(100) NOT NULL,
    documento_credenciales character varying(100),
    motivo_rechazo text NOT NULL,
    fecha_revision timestamp with time zone,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    estado character varying(20) NOT NULL,
    revisado_por_id bigint,
    usuario_id bigint NOT NULL
);

ALTER TABLE public.solicitudes_docente
    ADD CONSTRAINT fk_solicitudes_docente_estado
    FOREIGN KEY (estado) REFERENCES public.estados_solicitud_docente(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.solicitudes_docente
    ADD CONSTRAINT fk_solicitudes_docente_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.solicitudes_docente
    ADD CONSTRAINT fk_solicitudes_docente_revisor
    FOREIGN KEY (revisado_por_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_solicitudes_docente_estado ON public.solicitudes_docente (estado);
CREATE INDEX idx_solicitudes_docente_usuario ON public.solicitudes_docente (usuario_id);
CREATE INDEX idx_solicitudes_docente_revisor ON public.solicitudes_docente (revisado_por_id);

-- Fin del script 01
