-- ============================================================
-- 02_catalogo.sql — Catálogo de cursos y aprobación de docentes
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 8
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: niveles_curso (catálogo)
-- Básico, intermedio y avanzado.
-- ------------------------------------------------------------

CREATE TABLE public.niveles_curso (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: estados_curso (catálogo)
-- Ciclo de vida editorial de un curso: borrador, en revisión,
-- publicado o rechazado. El catálogo público solo muestra los
-- que están en estado PUBLICADO.
-- ------------------------------------------------------------

CREATE TABLE public.estados_curso (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: categorias
-- Categorías temáticas de los cursos (ej. Programación, Datos).
-- ------------------------------------------------------------

CREATE TABLE public.categorias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    descripcion text NOT NULL,

    CONSTRAINT uq_categorias_nombre UNIQUE (nombre),
    CONSTRAINT uq_categorias_slug UNIQUE (slug)
);


-- ------------------------------------------------------------
-- Tabla: cursos
-- Cursos de la plataforma. Cada curso pertenece a una categoría
-- y tiene un docente asignado. Las columnas de estado registran
-- el flujo de aprobación: el docente lo crea en BORRADOR, lo
-- envía a revisión (fecha_envio) y el administrador lo publica
-- (fecha_publicacion) o lo rechaza con notas_revision.
-- ------------------------------------------------------------

CREATE TABLE public.cursos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(10,2) NOT NULL,
    esta_activo boolean NOT NULL,
    es_mas_vendido boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    categoria_id bigint NOT NULL,
    instructor_id bigint,
    imagen_portada character varying(200) NOT NULL,
    idioma character varying(30) NOT NULL,
    resultados_aprendizaje text NOT NULL,
    requisitos text NOT NULL,
    nivel character varying(20) NOT NULL,
    notas_revision text NOT NULL,
    fecha_envio timestamp with time zone,
    fecha_publicacion timestamp with time zone,
    estado character varying(20) NOT NULL,

    CONSTRAINT uq_cursos_slug UNIQUE (slug)
);

ALTER TABLE public.cursos
    ADD CONSTRAINT fk_cursos_categoria
    FOREIGN KEY (categoria_id) REFERENCES public.categorias(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.cursos
    ADD CONSTRAINT fk_cursos_instructor
    FOREIGN KEY (instructor_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.cursos
    ADD CONSTRAINT fk_cursos_nivel
    FOREIGN KEY (nivel) REFERENCES public.niveles_curso(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.cursos
    ADD CONSTRAINT fk_cursos_estado
    FOREIGN KEY (estado) REFERENCES public.estados_curso(codigo)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_cursos_categoria ON public.cursos (categoria_id);
CREATE INDEX idx_cursos_instructor ON public.cursos (instructor_id);
CREATE INDEX idx_cursos_nivel ON public.cursos (nivel);
CREATE INDEX idx_cursos_estado ON public.cursos (estado);


-- ------------------------------------------------------------
-- Tabla: lecciones
-- Lecciones que componen un curso, ordenadas por la columna
-- "orden". El contenido puede ser un video, texto, o ambos.
-- ------------------------------------------------------------

CREATE TABLE public.lecciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo character varying(200) NOT NULL,
    orden integer NOT NULL,
    url_video character varying(200),
    contenido text,
    duracion_minutos integer NOT NULL,
    curso_id bigint NOT NULL
);

ALTER TABLE public.lecciones
    ADD CONSTRAINT fk_lecciones_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_lecciones_curso ON public.lecciones (curso_id);


-- ------------------------------------------------------------
-- Tabla: resenas
-- Calificación (1 a 5) y comentario que deja un alumno sobre un
-- curso. La restricción UNIQUE impide que la misma persona
-- reseñe dos veces el mismo curso.
-- ------------------------------------------------------------

CREATE TABLE public.resenas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calificacion integer NOT NULL,
    comentario text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    curso_id bigint NOT NULL,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_resenas_curso_usuario UNIQUE (curso_id, usuario_id)
);

ALTER TABLE public.resenas
    ADD CONSTRAINT fk_resenas_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.resenas
    ADD CONSTRAINT fk_resenas_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_resenas_curso ON public.resenas (curso_id);
CREATE INDEX idx_resenas_usuario ON public.resenas (usuario_id);


-- ------------------------------------------------------------
-- Tabla: estados_solicitud_cupo (catálogo)
-- Pendiente, aprobada o rechazada.
-- ------------------------------------------------------------

CREATE TABLE public.estados_solicitud_cupo (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: solicitudes_cupo
-- Un docente no puede publicar cursos sin límite: su plan de
-- membresía le da una cantidad de cupos. Para usar uno debe
-- solicitarlo al administrador describiendo el curso propuesto.
-- Cuando el docente crea el curso, la solicitud queda consumida
-- (esta_consumida) y se enlaza al curso creado.
-- ------------------------------------------------------------

CREATE TABLE public.solicitudes_cupo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_propuesto character varying(200) NOT NULL,
    justificacion text NOT NULL,
    motivo_rechazo text NOT NULL,
    fecha_revision timestamp with time zone,
    esta_consumida boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    curso_creado_id bigint,
    categoria_propuesta_id bigint,
    revisado_por_id bigint,
    estado character varying(20) NOT NULL,
    docente_id bigint NOT NULL,

    CONSTRAINT uq_solicitudes_cupo_curso_creado UNIQUE (curso_creado_id)
);

ALTER TABLE public.solicitudes_cupo
    ADD CONSTRAINT fk_solicitudes_cupo_estado
    FOREIGN KEY (estado) REFERENCES public.estados_solicitud_cupo(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.solicitudes_cupo
    ADD CONSTRAINT fk_solicitudes_cupo_docente
    FOREIGN KEY (docente_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.solicitudes_cupo
    ADD CONSTRAINT fk_solicitudes_cupo_revisor
    FOREIGN KEY (revisado_por_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.solicitudes_cupo
    ADD CONSTRAINT fk_solicitudes_cupo_categoria
    FOREIGN KEY (categoria_propuesta_id) REFERENCES public.categorias(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.solicitudes_cupo
    ADD CONSTRAINT fk_solicitudes_cupo_curso_creado
    FOREIGN KEY (curso_creado_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_solicitudes_cupo_estado ON public.solicitudes_cupo (estado);
CREATE INDEX idx_solicitudes_cupo_docente ON public.solicitudes_cupo (docente_id);
CREATE INDEX idx_solicitudes_cupo_revisor ON public.solicitudes_cupo (revisado_por_id);
CREATE INDEX idx_solicitudes_cupo_categoria ON public.solicitudes_cupo (categoria_propuesta_id);

-- Fin del script 02
