-- ============================================================
-- 03_ordenes.sql — Carrito, órdenes, cupones y ganancias
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 7
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: estados_orden (catálogo)
-- Pendiente, pagada, fallida o reembolsada.
-- ------------------------------------------------------------

CREATE TABLE public.estados_orden (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: carritos
-- Carrito de compras. Cada usuario tiene exactamente uno (1:1),
-- garantizado por la restricción UNIQUE sobre usuario_id.
-- ------------------------------------------------------------

CREATE TABLE public.carritos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_carritos_usuario UNIQUE (usuario_id)
);

ALTER TABLE public.carritos
    ADD CONSTRAINT fk_carritos_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;


-- ------------------------------------------------------------
-- Tabla: carrito_items
-- Cursos agregados al carrito. La restricción UNIQUE evita
-- agregar dos veces el mismo curso (no hay cantidad: un curso
-- se compra una sola vez).
-- ------------------------------------------------------------

CREATE TABLE public.carrito_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_agregado timestamp with time zone NOT NULL,
    carrito_id bigint NOT NULL,
    curso_id bigint NOT NULL,

    CONSTRAINT uq_carrito_items UNIQUE (carrito_id, curso_id)
);

ALTER TABLE public.carrito_items
    ADD CONSTRAINT fk_carrito_items_carrito
    FOREIGN KEY (carrito_id) REFERENCES public.carritos(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.carrito_items
    ADD CONSTRAINT fk_carrito_items_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_carrito_items_carrito ON public.carrito_items (carrito_id);
CREATE INDEX idx_carrito_items_curso ON public.carrito_items (curso_id);


-- ------------------------------------------------------------
-- Tabla: cupones
-- Códigos de descuento por porcentaje. "usos_maximos = 0"
-- significa ilimitado; "veces_usado" lleva la cuenta.
-- ------------------------------------------------------------

CREATE TABLE public.cupones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(30) NOT NULL,
    porcentaje_descuento numeric(5,2) NOT NULL,
    esta_activo boolean NOT NULL,
    valido_hasta timestamp with time zone,
    usos_maximos integer NOT NULL,
    veces_usado integer NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,

    CONSTRAINT uq_cupones_codigo UNIQUE (codigo)
);


-- ------------------------------------------------------------
-- Tabla: ordenes
-- Compra confirmada. Solo se guardan los 4 últimos dígitos de
-- la tarjeta (card_last4): nunca el número completo ni el CVV,
-- por cumplimiento PCI-DSS. El descuento aplicado se congela en
-- monto_descuento para que el histórico no cambie si el cupón
-- se modifica después.
-- ------------------------------------------------------------

CREATE TABLE public.ordenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado character varying(20) NOT NULL,
    monto_total numeric(10,2) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL,
    ultimos4_tarjeta character varying(4) NOT NULL,
    cupon_id bigint,
    monto_descuento numeric(10,2) NOT NULL,
    referencia_transaccion character varying(200) NOT NULL
);

ALTER TABLE public.ordenes
    ADD CONSTRAINT fk_ordenes_estado
    FOREIGN KEY (estado) REFERENCES public.estados_orden(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.ordenes
    ADD CONSTRAINT fk_ordenes_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.ordenes
    ADD CONSTRAINT fk_ordenes_cupon
    FOREIGN KEY (cupon_id) REFERENCES public.cupones(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_ordenes_usuario ON public.ordenes (usuario_id);
CREATE INDEX idx_ordenes_cupon ON public.ordenes (cupon_id);
CREATE INDEX idx_ordenes_estado ON public.ordenes (estado);
CREATE INDEX idx_ordenes_estado_fecha ON public.ordenes (estado, fecha_creacion);
CREATE INDEX idx_ordenes_usuario_fecha ON public.ordenes (usuario_id, fecha_creacion);


-- ------------------------------------------------------------
-- Tabla: orden_items
-- Cursos incluidos en una orden. El precio se congela al
-- momento de la compra (precio_al_comprar): si el curso sube de
-- precio después, la orden histórica no cambia.
-- ------------------------------------------------------------

CREATE TABLE public.orden_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    precio_al_comprar numeric(10,2) NOT NULL,
    curso_id bigint NOT NULL,
    orden_id bigint NOT NULL
);

ALTER TABLE public.orden_items
    ADD CONSTRAINT fk_orden_items_orden
    FOREIGN KEY (orden_id) REFERENCES public.ordenes(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.orden_items
    ADD CONSTRAINT fk_orden_items_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_orden_items_orden ON public.orden_items (orden_id);
CREATE INDEX idx_orden_items_curso ON public.orden_items (curso_id);


-- ------------------------------------------------------------
-- Tabla: ganancias_docente
-- Comisión que gana el instructor por cada curso vendido. La
-- tasa se congela en el momento de la venta (tasa_comision),
-- porque depende del plan de membresía que el docente tenía
-- entonces: si luego cambia de plan, lo ya ganado no se altera.
-- La restricción UNIQUE sobre orden_item_id garantiza que una
-- misma venta no genere la comisión dos veces.
-- ------------------------------------------------------------

CREATE TABLE public.ganancias_docente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto_bruto numeric(10,2) NOT NULL,
    tasa_comision numeric(4,2) NOT NULL,
    monto_neto numeric(10,2) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    curso_id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    orden_item_id bigint NOT NULL,

    CONSTRAINT uq_ganancias_docente_orden_item UNIQUE (orden_item_id)
);

ALTER TABLE public.ganancias_docente
    ADD CONSTRAINT fk_ganancias_docente_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.ganancias_docente
    ADD CONSTRAINT fk_ganancias_docente_instructor
    FOREIGN KEY (instructor_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.ganancias_docente
    ADD CONSTRAINT fk_ganancias_docente_orden_item
    FOREIGN KEY (orden_item_id) REFERENCES public.orden_items(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_ganancias_docente_curso ON public.ganancias_docente (curso_id);
CREATE INDEX idx_ganancias_docente_instructor ON public.ganancias_docente (instructor_id);
CREATE INDEX idx_ganancias_docente_instructor_fecha
    ON public.ganancias_docente (instructor_id, fecha_creacion);

-- Fin del script 03
