-- ============================================================
-- 04_membresias.sql — Planes de membresía y suscripciones
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 7
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: ciclos_facturacion (catálogo)
-- Mensual o anual.
-- ------------------------------------------------------------

CREATE TABLE public.ciclos_facturacion (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: audiencias_plan (catálogo)
-- A quién va dirigido el plan: ALUMNO o DOCENTE. Son dos
-- familias de planes con beneficios distintos — el alumno
-- obtiene descuentos, el docente obtiene cupos y comisión.
-- ------------------------------------------------------------

CREATE TABLE public.audiencias_plan (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: niveles_plan (catálogo)
-- Escalón del plan dentro de su familia (bronce, plata, oro).
-- La columna "rango" permite ordenarlos y compararlos.
-- ------------------------------------------------------------

CREATE TABLE public.niveles_plan (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    rango integer NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: estados_membresia (catálogo)
-- Activa, cancelada o expirada.
-- ------------------------------------------------------------

CREATE TABLE public.estados_membresia (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: planes_membresia
-- Planes disponibles. Según la audiencia se usan unas columnas
-- u otras:
--   ALUMNO  -> porcentaje_descuento_miembro (descuento en compras)
--   DOCENTE -> cupos_curso (cuántos cursos puede publicar) y
--              porcentaje_comision_instructor (cuánto se lleva
--              de cada venta; el plan Oro da 0.80 = 80%)
-- ------------------------------------------------------------

CREATE TABLE public.planes_membresia (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    ciclo_facturacion character varying(20) NOT NULL,
    precio numeric(8,2) NOT NULL,
    porcentaje_descuento numeric(5,2) NOT NULL,
    esta_activo boolean NOT NULL,
    limite_cursos integer NOT NULL,
    porcentaje_descuento_miembro numeric(5,2) NOT NULL,
    cupos_curso integer NOT NULL,
    porcentaje_comision_instructor numeric(4,2) NOT NULL,
    audiencia character varying(20) NOT NULL,
    nivel character varying(20) NOT NULL
);

ALTER TABLE public.planes_membresia
    ADD CONSTRAINT fk_planes_ciclo
    FOREIGN KEY (ciclo_facturacion) REFERENCES public.ciclos_facturacion(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.planes_membresia
    ADD CONSTRAINT fk_planes_audiencia
    FOREIGN KEY (audiencia) REFERENCES public.audiencias_plan(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.planes_membresia
    ADD CONSTRAINT fk_planes_nivel
    FOREIGN KEY (nivel) REFERENCES public.niveles_plan(codigo)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_planes_ciclo ON public.planes_membresia (ciclo_facturacion);
CREATE INDEX idx_planes_audiencia ON public.planes_membresia (audiencia);
CREATE INDEX idx_planes_nivel ON public.planes_membresia (nivel);


-- ------------------------------------------------------------
-- Tabla: membresias_usuario
-- Suscripción de un usuario a un plan. La restricción UNIQUE
-- (usuario_id, audiencia) permite que una misma persona tenga a
-- la vez una membresía de alumno y una de docente, pero no dos
-- de la misma familia.
-- ------------------------------------------------------------

CREATE TABLE public.membresias_usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado character varying(20) NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_expiracion timestamp with time zone NOT NULL,
    fecha_cancelacion timestamp with time zone,
    renovacion_automatica boolean NOT NULL,
    plan_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    audiencia character varying(20) NOT NULL,

    CONSTRAINT uq_membresias_usuario_audiencia UNIQUE (usuario_id, audiencia)
);

ALTER TABLE public.membresias_usuario
    ADD CONSTRAINT fk_membresias_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.membresias_usuario
    ADD CONSTRAINT fk_membresias_plan
    FOREIGN KEY (plan_id) REFERENCES public.planes_membresia(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.membresias_usuario
    ADD CONSTRAINT fk_membresias_estado
    FOREIGN KEY (estado) REFERENCES public.estados_membresia(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.membresias_usuario
    ADD CONSTRAINT fk_membresias_audiencia
    FOREIGN KEY (audiencia) REFERENCES public.audiencias_plan(codigo)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_membresias_usuario ON public.membresias_usuario (usuario_id);
CREATE INDEX idx_membresias_plan ON public.membresias_usuario (plan_id);
CREATE INDEX idx_membresias_estado ON public.membresias_usuario (estado);
CREATE INDEX idx_membresias_audiencia ON public.membresias_usuario (audiencia);


-- ------------------------------------------------------------
-- Tabla: pagos_membresia
-- Historial de cobros de una membresía. Igual que en las
-- órdenes, solo se guardan los 4 últimos dígitos de la tarjeta.
-- ------------------------------------------------------------

CREATE TABLE public.pagos_membresia (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto numeric(8,2) NOT NULL,
    ultimos4_tarjeta character varying(4) NOT NULL,
    fecha_pago timestamp with time zone NOT NULL,
    referencia_transaccion character varying(200) NOT NULL,
    fue_exitoso boolean NOT NULL,
    membresia_id bigint NOT NULL
);

ALTER TABLE public.pagos_membresia
    ADD CONSTRAINT fk_pagos_membresia
    FOREIGN KEY (membresia_id) REFERENCES public.membresias_usuario(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_pagos_membresia ON public.pagos_membresia (membresia_id);

-- Fin del script 04
