-- ============================================================
-- 05_biblioteca.sql — Biblioteca del alumno: inscripciones,
-- progreso, certificados, lista de deseos, rachas y medallas
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 8
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: tipos_inscripcion (catálogo)
-- Cómo obtuvo el alumno el acceso al curso: COMPRA (lo pagó) o
-- MEMBRESIA (lo incluye su plan).
-- ------------------------------------------------------------

CREATE TABLE public.tipos_inscripcion (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: inscripciones
-- Inscripción de un usuario a un curso. El porcentaje_avance se
-- recalcula por señal cada vez que se completa una lección.
-- La restricción UNIQUE impide inscribirse dos veces al mismo
-- curso.
-- ------------------------------------------------------------

CREATE TABLE public.inscripciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_inscripcion character varying(20) NOT NULL,
    fecha_inscripcion timestamp with time zone NOT NULL,
    porcentaje_avance double precision NOT NULL,
    esta_completado boolean NOT NULL,
    curso_id bigint NOT NULL,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_inscripciones_curso_usuario UNIQUE (curso_id, usuario_id)
);

ALTER TABLE public.inscripciones
    ADD CONSTRAINT fk_inscripciones_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.inscripciones
    ADD CONSTRAINT fk_inscripciones_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.inscripciones
    ADD CONSTRAINT fk_inscripciones_tipo
    FOREIGN KEY (tipo_inscripcion) REFERENCES public.tipos_inscripcion(codigo)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_inscripciones_curso ON public.inscripciones (curso_id);
CREATE INDEX idx_inscripciones_usuario ON public.inscripciones (usuario_id);
CREATE INDEX idx_inscripciones_tipo ON public.inscripciones (tipo_inscripcion);


-- ------------------------------------------------------------
-- Tabla: progreso_lecciones
-- Avance del alumno en cada lección. Existe una fila por
-- (inscripción, lección), garantizado por la UNIQUE.
-- ------------------------------------------------------------

CREATE TABLE public.progreso_lecciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    esta_completado boolean NOT NULL,
    fecha_completado timestamp with time zone,
    porcentaje_visto double precision NOT NULL,
    inscripcion_id bigint NOT NULL,
    leccion_id bigint NOT NULL,

    CONSTRAINT uq_progreso_inscripcion_leccion UNIQUE (inscripcion_id, leccion_id)
);

ALTER TABLE public.progreso_lecciones
    ADD CONSTRAINT fk_progreso_inscripcion
    FOREIGN KEY (inscripcion_id) REFERENCES public.inscripciones(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.progreso_lecciones
    ADD CONSTRAINT fk_progreso_leccion
    FOREIGN KEY (leccion_id) REFERENCES public.lecciones(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_progreso_inscripcion ON public.progreso_lecciones (inscripcion_id);
CREATE INDEX idx_progreso_leccion ON public.progreso_lecciones (leccion_id);


-- ------------------------------------------------------------
-- Tabla: certificados
-- Certificado emitido al completar el curso y aprobar el examen
-- final. El código_verificacion (UUID) permite validarlo desde
-- fuera. El título del curso, el nombre del alumno y la duración
-- se COPIAN aquí a propósito: si el curso cambia de nombre o el
-- alumno cambia el suyo, el certificado ya emitido no se altera.
-- ------------------------------------------------------------

CREATE TABLE public.certificados (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_emision timestamp with time zone NOT NULL,
    codigo_verificacion uuid NOT NULL,
    inscripcion_id bigint NOT NULL,
    fecha_completado timestamp with time zone,
    duracion_curso_horas numeric(5,2) NOT NULL,
    titulo_curso character varying(200) NOT NULL,
    nombre_alumno character varying(200) NOT NULL,

    CONSTRAINT uq_certificados_inscripcion UNIQUE (inscripcion_id),
    CONSTRAINT uq_certificados_codigo UNIQUE (codigo_verificacion)
);

ALTER TABLE public.certificados
    ADD CONSTRAINT fk_certificados_inscripcion
    FOREIGN KEY (inscripcion_id) REFERENCES public.inscripciones(id)
    DEFERRABLE INITIALLY DEFERRED;


-- ------------------------------------------------------------
-- Tabla: lista_deseos
-- Cursos que el alumno guardó para después.
-- ------------------------------------------------------------

CREATE TABLE public.lista_deseos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_agregado timestamp with time zone NOT NULL,
    curso_id bigint NOT NULL,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_lista_deseos UNIQUE (curso_id, usuario_id)
);

ALTER TABLE public.lista_deseos
    ADD CONSTRAINT fk_lista_deseos_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.lista_deseos
    ADD CONSTRAINT fk_lista_deseos_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_lista_deseos_curso ON public.lista_deseos (curso_id);
CREATE INDEX idx_lista_deseos_usuario ON public.lista_deseos (usuario_id);


-- ------------------------------------------------------------
-- Tabla: rachas_estudio
-- Días seguidos estudiando. Una fila por usuario (UNIQUE).
-- ------------------------------------------------------------

CREATE TABLE public.rachas_estudio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    racha_actual integer NOT NULL,
    racha_maxima integer NOT NULL,
    fecha_ultima_actividad date,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_rachas_usuario UNIQUE (usuario_id)
);

ALTER TABLE public.rachas_estudio
    ADD CONSTRAINT fk_rachas_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;


-- ------------------------------------------------------------
-- Tabla: medallas (catálogo)
-- Catálogo de logros que puede conseguir un alumno (primer
-- curso, examen perfecto, racha de 30 días...). El ícono y el
-- orden son editables desde el panel de administración sin
-- necesidad de tocar el código.
-- ------------------------------------------------------------

CREATE TABLE public.medallas (
    codigo character varying(30) PRIMARY KEY,
    nombre character varying(80) NOT NULL,
    descripcion character varying(200) NOT NULL,
    icono character varying(8) NOT NULL,
    orden smallint NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: medallas_usuario
-- Medallas conseguidas por cada alumno. La UNIQUE evita
-- otorgar dos veces la misma.
-- ------------------------------------------------------------

CREATE TABLE public.medallas_usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_obtencion timestamp with time zone NOT NULL,
    medalla character varying(30) NOT NULL,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_medallas_usuario UNIQUE (medalla, usuario_id)
);

ALTER TABLE public.medallas_usuario
    ADD CONSTRAINT fk_medallas_usuario_medalla
    FOREIGN KEY (medalla) REFERENCES public.medallas(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.medallas_usuario
    ADD CONSTRAINT fk_medallas_usuario_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_medallas_usuario_medalla ON public.medallas_usuario (medalla);
CREATE INDEX idx_medallas_usuario_usuario ON public.medallas_usuario (usuario_id);

-- Fin del script 05
