-- ============================================================
-- 06_examenes.sql — Examen final, intentos y respuestas
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 5
-- ============================================================
-- El alumno rinde el examen final al completar todas las
-- lecciones. Si lo aprueba, se emite el certificado.
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: examenes
-- Examen final del curso. Relación 1:1 con el curso, impuesta
-- por la restricción UNIQUE sobre curso_id.
-- "intentos_maximos = 0" significa intentos ilimitados.
-- El tiempo límite lo controla el servidor, no el navegador.
-- ------------------------------------------------------------

CREATE TABLE public.examenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo character varying(200) NOT NULL,
    instrucciones text NOT NULL,
    tiempo_limite_minutos integer NOT NULL,
    nota_aprobacion numeric(5,2) NOT NULL,
    intentos_maximos integer NOT NULL,
    esta_activo boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    curso_id bigint NOT NULL,

    CONSTRAINT uq_examenes_curso UNIQUE (curso_id)
);

ALTER TABLE public.examenes
    ADD CONSTRAINT fk_examenes_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;


-- ------------------------------------------------------------
-- Tabla: preguntas
-- Preguntas de un examen, ordenadas por la columna "orden".
-- Cada pregunta vale una cantidad de "puntos".
-- ------------------------------------------------------------

CREATE TABLE public.preguntas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto text NOT NULL,
    orden integer NOT NULL,
    puntos integer NOT NULL,
    examen_id bigint NOT NULL
);

ALTER TABLE public.preguntas
    ADD CONSTRAINT fk_preguntas_examen
    FOREIGN KEY (examen_id) REFERENCES public.examenes(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_preguntas_examen ON public.preguntas (examen_id);


-- ------------------------------------------------------------
-- Tabla: opciones_respuesta
-- Opciones de respuesta de cada pregunta (opción múltiple).
--
-- IMPORTANTE: la columna "es_correcta" NUNCA se expone en la
-- API pública. El serializer que envía el examen al navegador
-- la omite deliberadamente, para que el alumno no pueda leer
-- las respuestas correctas inspeccionando la red.
-- ------------------------------------------------------------

CREATE TABLE public.opciones_respuesta (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto character varying(300) NOT NULL,
    es_correcta boolean NOT NULL,
    pregunta_id bigint NOT NULL
);

ALTER TABLE public.opciones_respuesta
    ADD CONSTRAINT fk_opciones_pregunta
    FOREIGN KEY (pregunta_id) REFERENCES public.preguntas(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_opciones_pregunta ON public.opciones_respuesta (pregunta_id);


-- ------------------------------------------------------------
-- Tabla: intentos_examen
-- Cada vez que un alumno rinde el examen. Se enlaza a la
-- INSCRIPCIÓN (no al usuario) porque el examen pertenece al
-- curso en el que está inscrito.
-- La UNIQUE (inscripcion_id, numero_intento) numera los
-- intentos de forma consecutiva sin repetirse.
-- Si el tiempo se agota, el intento se cierra con nota 0.
-- ------------------------------------------------------------

CREATE TABLE public.intentos_examen (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_intento integer NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_envio timestamp with time zone,
    nota numeric(5,2),
    aprobado boolean NOT NULL,
    inscripcion_id bigint NOT NULL,

    CONSTRAINT uq_intentos_inscripcion_numero UNIQUE (numero_intento, inscripcion_id)
);

ALTER TABLE public.intentos_examen
    ADD CONSTRAINT fk_intentos_inscripcion
    FOREIGN KEY (inscripcion_id) REFERENCES public.inscripciones(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_intentos_inscripcion ON public.intentos_examen (inscripcion_id);


-- ------------------------------------------------------------
-- Tabla: respuestas_intento
-- Respuesta que dio el alumno a cada pregunta en un intento.
-- "opcion_elegida_id" admite NULL: la pregunta pudo quedar sin
-- responder (por ejemplo si se agotó el tiempo).
-- "es_correcta" es una foto del momento de calificar: si luego
-- se corrige cuál era la opción correcta, las notas ya dadas no
-- cambian retroactivamente.
-- ------------------------------------------------------------

CREATE TABLE public.respuestas_intento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    es_correcta boolean NOT NULL,
    opcion_elegida_id bigint,
    intento_id bigint NOT NULL,
    pregunta_id bigint NOT NULL,

    CONSTRAINT uq_respuestas_intento_pregunta UNIQUE (intento_id, pregunta_id)
);

ALTER TABLE public.respuestas_intento
    ADD CONSTRAINT fk_respuestas_intento
    FOREIGN KEY (intento_id) REFERENCES public.intentos_examen(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.respuestas_intento
    ADD CONSTRAINT fk_respuestas_pregunta
    FOREIGN KEY (pregunta_id) REFERENCES public.preguntas(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.respuestas_intento
    ADD CONSTRAINT fk_respuestas_opcion
    FOREIGN KEY (opcion_elegida_id) REFERENCES public.opciones_respuesta(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_respuestas_intento ON public.respuestas_intento (intento_id);
CREATE INDEX idx_respuestas_pregunta ON public.respuestas_intento (pregunta_id);
CREATE INDEX idx_respuestas_opcion ON public.respuestas_intento (opcion_elegida_id);

-- Fin del script 06
