-- ============================================================
-- 07_recomendaciones.sql — Motor de recomendaciones (ML/SVD)
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 3
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: tipos_interaccion (catálogo)
-- Qué hizo el usuario con el curso: verlo, agregarlo a la lista
-- de deseos, comprarlo, reseñarlo. Cada tipo tiene un "peso"
-- configurable: una compra vale mucho más que una visita como
-- señal de interés, y ese peso alimenta el modelo.
-- ------------------------------------------------------------

CREATE TABLE public.tipos_interaccion (
    codigo character varying(20) PRIMARY KEY,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL,
    peso double precision NOT NULL
);


-- ------------------------------------------------------------
-- Tabla: interacciones_usuario_curso
-- Matriz de entrada del modelo de filtrado colaborativo. Cada
-- fila dice "este usuario interactuó así con este curso".
-- El índice compuesto (usuario_id, curso_id) acelera la
-- construcción de la matriz durante el entrenamiento nocturno.
-- ------------------------------------------------------------

CREATE TABLE public.interacciones_usuario_curso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_interaccion character varying(20) NOT NULL,
    peso double precision NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    curso_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);

ALTER TABLE public.interacciones_usuario_curso
    ADD CONSTRAINT fk_interacciones_tipo
    FOREIGN KEY (tipo_interaccion) REFERENCES public.tipos_interaccion(codigo)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.interacciones_usuario_curso
    ADD CONSTRAINT fk_interacciones_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.interacciones_usuario_curso
    ADD CONSTRAINT fk_interacciones_curso
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_interacciones_usuario ON public.interacciones_usuario_curso (usuario_id);
CREATE INDEX idx_interacciones_curso ON public.interacciones_usuario_curso (curso_id);
CREATE INDEX idx_interacciones_tipo ON public.interacciones_usuario_curso (tipo_interaccion);
CREATE INDEX idx_interacciones_usuario_curso
    ON public.interacciones_usuario_curso (usuario_id, curso_id);


-- ------------------------------------------------------------
-- Tabla: cache_recomendaciones
-- Resultado ya calculado del modelo SVD para cada usuario. Se
-- guarda como un arreglo JSON de IDs de curso, en orden de
-- relevancia.
--
-- Existe para no ejecutar el modelo en cada petición: una tarea
-- programada (Celery, 3 a.m.) reentrena y actualiza esta tabla,
-- y la API solo lee de aquí. Una fila por usuario (UNIQUE).
-- ------------------------------------------------------------

CREATE TABLE public.cache_recomendaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ids_cursos_recomendados jsonb NOT NULL,
    ultima_actualizacion timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL,

    CONSTRAINT uq_cache_recomendaciones_usuario UNIQUE (usuario_id)
);

ALTER TABLE public.cache_recomendaciones
    ADD CONSTRAINT fk_cache_recomendaciones_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

-- Fin del script 07
