-- ============================================================
-- 08_analitica.sql — Analítica de navegación y conversión
-- Proyecto: E-Commerce de Cursos Tecnológicos
-- Motor: PostgreSQL 17
-- Tablas: 2
-- ============================================================
-- Alimentan el dashboard del administrador y, junto con las
-- interacciones, el motor de recomendaciones.
-- ============================================================

-- ------------------------------------------------------------
-- Tabla: registros_navegacion
-- Bitácora de eventos del sitio: búsquedas, vistas de curso,
-- adiciones al carrito, compras. Funciona tanto para usuarios
-- autenticados (usuario_id) como anónimos (id_sesion), por eso
-- usuario_id admite NULL.
--
-- "metadatos" es JSONB: guarda el detalle variable de cada tipo
-- de evento (el término buscado, los filtros aplicados...) sin
-- necesidad de una columna por caso.
--
-- Los índices compuestos con la fecha sirven para las consultas
-- del dashboard, que siempre filtran por rango de tiempo.
-- ------------------------------------------------------------

CREATE TABLE public.registros_navegacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion character varying(255) NOT NULL,
    tipo_evento character varying(30) NOT NULL,
    metadatos jsonb NOT NULL,
    direccion_ip inet,
    agente_usuario text NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    usuario_id bigint
);

ALTER TABLE public.registros_navegacion
    ADD CONSTRAINT fk_registros_navegacion_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_registros_usuario ON public.registros_navegacion (usuario_id);
CREATE INDEX idx_registros_sesion ON public.registros_navegacion (id_sesion);
CREATE INDEX idx_registros_fecha ON public.registros_navegacion (fecha_hora);
CREATE INDEX idx_registros_usuario_fecha ON public.registros_navegacion (usuario_id, fecha_hora);
CREATE INDEX idx_registros_evento_fecha ON public.registros_navegacion (tipo_evento, fecha_hora);


-- ------------------------------------------------------------
-- Tabla: embudo_conversion
-- Etapa más avanzada que alcanzó cada sesión en el recorrido
-- de compra: VISTA -> CARRITO -> CHECKOUT -> COMPRA.
--
-- Permite responder la pregunta de negocio "¿cuántos llegaron
-- al carrito pero no compraron?" sin recorrer toda la bitácora
-- de navegación.
-- ------------------------------------------------------------

CREATE TABLE public.embudo_conversion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion character varying(255) NOT NULL,
    etapa character varying(15) NOT NULL,
    curso_id integer,
    fecha_alcanzada timestamp with time zone NOT NULL,
    usuario_id bigint
);

ALTER TABLE public.embudo_conversion
    ADD CONSTRAINT fk_embudo_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_embudo_usuario ON public.embudo_conversion (usuario_id);
CREATE INDEX idx_embudo_sesion ON public.embudo_conversion (id_sesion);
CREATE INDEX idx_embudo_sesion_etapa ON public.embudo_conversion (id_sesion, etapa);
CREATE INDEX idx_embudo_etapa_fecha ON public.embudo_conversion (etapa, fecha_alcanzada);

-- Fin del script 08
